name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: ubuntu-latest
            platform: mingw
            arch: x64
            flags: --no-color
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: |
          sudo apt update
          sudo apt install mingw-w64
        if: ${{ matrix.platform == 'mingw' }}
      - run: npm install -g bare-runtime bare-make
      - run: npm install
      - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}  ${{ matrix.flags }} --debug
      - run: bare-make build
      - run: bare-make install
      - run: npm test
