name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: ubuntu-latest
            platform: mingw
            arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: |
          choco install msys2
          "C:\tools\msys64" | Out-File -FilePath "$env:GITHUB_PATH" -Append
        if: ${{ matrix.platform == 'mingw' }}
      - run: pacman --noconfirm -S make
        shell: C:\tools\msys64\usr\bin\bash.exe -e {0}
        env:
          PATH: C:\tools\msys64\usr\bin
        if: ${{ matrix.platform == 'mingw' }}
      - run: npm install -g bare-runtime bare-make
      - run: npm install
      - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --debug
      - run: bare-make build
      - run: bare-make install
      - run: npm test
